name: infra-setup-redis

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      - "16379:16379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=secret
      - REDIS_REPLICAOF=127.0.0.1 6379
      - REDIS_MASTERAUTH=secret
    container_name: infra-redis
    command: redis-server --requirepass runRedisN0w
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - /Volumes/Expansion/var/infra/redis:/data
      - /etc/redis.conf:/usr/local/etc/redis/redis.conf